/**
 * Cross-language runtime contract gate for the shared fixture.
 *
 * `tests/fixtures/runtime_contract/fixtures.json` is regenerated by the Python
 * gate from the real production projection, so it is the one sample both
 * languages agree on.  This test drives those exact wire values (never a copy)
 * through the real protocol client over a fake socket and through the real
 * console reducer, and pins the three properties the contract promises:
 *
 * 1. every fixture event reaches the view untouched, including an unknown
 *    future kind with fields no v1 client knows (payload preserved) and the
 *    bare-string `info` payload; every legal fixture event carries the frozen
 *    v1 envelope `version`, so a fake future version cannot creep in as a
 *    "compatible" sample;
 * 2. the reducer folds the known kinds and ignores the unknown one without
 *    polluting the transcript / usage / approval state it already held;
 * 3. `runtime.session.get` returns the fixture snapshot as the declared
 *    `SessionView`.
 *
 * A final declaration gate proves `runtime-client/types.ts` only re-exports the
 * generated contract and never redeclares a wire interface (which would drift
 * silently from the Python registry).
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';

import { SynapseRuntimeClient } from '../src/runtime-client/SynapseRuntimeClient.ts';
import type { SocketLike } from '../src/runtime-client/SynapseRuntimeClient.ts';
import type { RuntimeEvent } from '../src/runtime-client/types.ts';
import { EVENT_VERSION } from '../src/runtime-client/contract.generated.ts';
import {
  reduceRuntimeEvent,
  type LiveReducibleState,
} from '../src/stores/liveEventReducer.ts';

const here = dirname(fileURLToPath(import.meta.url));
const webRoot = join(here, '..');
const repoRoot = join(webRoot, '..');

/** The shared, language-neutral fixture (regenerated by the Python gate). */
const FIXTURE_PATH = join(repoRoot, 'tests', 'fixtures', 'runtime_contract', 'fixtures.json');
const fixture = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8')) as {
  contract_version: number;
  wire_version: string;
  events: Array<{ name: string; kind: string; wire: RuntimeEvent }>;
  session_read: {
    method: string;
    request: { session: { project_id: string; thread_id: string } };
    result: Record<string, unknown>;
  };
};

const SESSION = fixture.session_read.request.session;
const CAPABILITIES = {
  legacy_v1: true,
  raw_cursor: true,
  watch_resume: true,
  approval_resume: true,
};

interface SentFrame {
  id: number;
  method: string;
  params: any;
}

/**
 * Fake transport: answers the handshake, the watch and the session snapshot,
 * and can deliver fixture events exactly as the relay would.
 */
class FixtureSocket implements SocketLike {
  readyState = 0;
  onopen: (() => void) | null = null;
  onmessage: ((ev: { data: any }) => void) | null = null;
  onerror: (() => void) | null = null;
  onclose: ((ev?: { code?: number; reason?: string }) => void) | null = null;
  sent: SentFrame[] = [];

  send(data: string): void {
    const request = JSON.parse(data) as SentFrame;
    this.sent.push(request);
    this.push({
      jsonrpc: '2.0',
      id: request.id,
      meta: { wire_version: fixture.wire_version },
      result: this.reply(request),
    });
  }

  reply(request: SentFrame): unknown {
    switch (request.method) {
      case 'runtime.protocol.negotiate':
        return {
          wire_version: fixture.wire_version,
          supported_versions: [fixture.wire_version],
          capabilities: CAPABILITIES,
        };
      case 'runtime.session.get':
        return fixture.session_read.result;
      case 'runtime.events.watch':
        return { subscription_id: 'sub-1', cursor: request.params.after ?? 0 };
      default:
        return {};
    }
  }

  push(frame: unknown): void {
    this.onmessage?.({ data: typeof frame === 'string' ? frame : JSON.stringify(frame) });
  }

  /** Deliver one fixture event as a live `runtime.event` notification. */
  notify(event: RuntimeEvent): void {
    this.push({
      jsonrpc: '2.0',
      method: 'runtime.event',
      params: { subscription_id: 'sub-1', cursor: event.sequence, event },
    });
  }

  serverOpen(): void {
    this.readyState = 1;
    this.onopen?.();
  }

  close(): void {
    if (this.readyState === 3) return;
    this.readyState = 3;
    const cb = this.onclose;
    this.onclose = null;
    cb?.();
  }
}

function makeClient(onEvent: (event: RuntimeEvent) => void): {
  client: SynapseRuntimeClient;
  socket: FixtureSocket;
} {
  const socket = new FixtureSocket();
  const client = new SynapseRuntimeClient({
    url: 'ws://core',
    socketFactory: () => socket,
    onEvent: (event) => onEvent(event),
  });
  return { client, socket };
}

function baseState(): LiveReducibleState {
  return {
    messages: [],
    activeTurnId: null,
    runtimeStatus: 'idle',
    steerQueueCount: 0,
    pendingApproval: null,
    activity: null,
    usage: null,
    metricsLabel: '',
  };
}

const at = new Date(0);
const now = () => at;

test('the live client delivers every fixture event, unknown kind and fields included', async () => {
  const received: RuntimeEvent[] = [];
  const { client, socket } = makeClient((event) => received.push(event));

  const connecting = client.connect();
  socket.serverOpen();
  await connecting;

  await client.watchEvents(SESSION, 0);
  for (const entry of fixture.events) socket.notify(entry.wire);

  assert.deepEqual(
    received.map((event) => event.kind),
    fixture.events.map((entry) => entry.kind),
  );
  assert.deepEqual(
    received.map((event) => event.sequence),
    fixture.events.map((entry) => entry.wire.sequence),
  );
  // Every legal fixture event carries the frozen v1 envelope version, and the
  // client delivers exactly that version (never a rewritten one).
  assert.ok(
    fixture.events.every((entry) => entry.wire.version === EVENT_VERSION),
    'the shared fixture must use the real v1 event version',
  );
  assert.deepEqual(
    received.map((event) => event.version),
    fixture.events.map(() => EVENT_VERSION),
  );
  // The bare-string `info` payload survives as a string (no wrapper invented).
  const info = received.find((event) => event.kind === 'info');
  assert.equal(typeof info?.payload, 'string');
  // The unknown future kind passes through with every unknown field intact.
  const future = received.find((event) => event.kind === 'future_kind');
  assert.deepEqual(future?.payload, fixture.events[2]?.wire.payload);
  assert.equal((future?.payload as { details?: { count?: number } })?.details?.count, 2);
  // The watch cursor tracks the fixture's own sequences.
  assert.equal(client.getWatchCursor(), fixture.events[fixture.events.length - 1]?.wire.sequence);

  client.disconnect();
});

test('the console reducer folds known fixture events and ignores the unknown kind', () => {
  const [info, answerDelta, future] = fixture.events;
  let state = baseState();

  state = { ...state, ...reduceRuntimeEvent(state, info.wire, now) };
  assert.equal(state.messages.length, 1);
  assert.equal(state.messages[0]?.type, 'info');
  assert.equal(state.messages[0]?.content, 'a plain string payload');

  state = { ...state, ...reduceRuntimeEvent(state, answerDelta.wire, now) };
  assert.equal(state.messages.length, 2);
  assert.equal(state.messages[1]?.type, 'assistant');
  assert.equal(state.messages[1]?.content, 'hello');

  // The unknown kind adds nothing and leaves the existing UI state untouched.
  const before = state;
  const patch = reduceRuntimeEvent(state, future.wire, now);
  assert.equal('messages' in patch, false);
  assert.equal('usage' in patch, false);
  assert.equal('pendingApproval' in patch, false);
  const after = { ...state, ...patch };
  assert.deepEqual(after.messages, before.messages);
  assert.equal(after.usage, before.usage);
  assert.equal(after.pendingApproval, before.pendingApproval);
  assert.equal(after.messages.length, 2);
});

test('runtime.session.get returns the fixture snapshot as the declared SessionView', async () => {
  const { client, socket } = makeClient(() => {});
  const connecting = client.connect();
  socket.serverOpen();
  await connecting;

  const view = await client.getSession(SESSION);
  assert.deepEqual(view, fixture.session_read.result);
  assert.equal(view.status, 'idle');
  assert.equal(view.latest_sequence, 12);
  assert.equal(view.usage.input_tokens, 10);
  // The projection carries no runtime handle and no UI-only wall-clock field.
  assert.equal('opened_at' in view, false);
  assert.equal('handle' in view, false);

  client.disconnect();
});

test('types.ts only re-exports the generated contract and redeclares no wire shape', () => {
  const typesText = readFileSync(join(webRoot, 'src', 'runtime-client', 'types.ts'), 'utf8');
  assert.equal(/^\s*export\s+interface\s/m.test(typesText), false, 'types.ts must not declare a wire interface');
  assert.equal(/^\s*export\s+type\s+[A-Za-z0-9_]+\s*=/m.test(typesText), false, 'types.ts must not redeclare a wire type alias');

  const block = /export\s+type\s*\{([^}]*)\}\s*from\s*'\.\/contract\.generated\.ts';/.exec(typesText);
  assert.ok(block, 'types.ts must re-export the generated contract');
  const reexported = block[1]
    .split(',')
    .map((name) => name.trim())
    .filter((name) => name !== '');
  assert.ok(reexported.length >= 30, 'types.ts must re-export the wire DTO surface');

  const generated = readFileSync(
    join(webRoot, 'src', 'runtime-client', 'contract.generated.ts'),
    'utf8',
  );
  const declared = new Set(
    [...generated.matchAll(/export\s+(?:interface|type|const)\s+([A-Za-z0-9_]+)/g)].map((m) => m[1]),
  );
  for (const name of reexported) {
    assert.equal(declared.has(name), true, `${name} must be exported by the generated contract`);
  }
  // The drift-prone DTOs must resolve through the generated contract.
  for (const name of ['RuntimeEvent', 'CommandReceipt', 'OpenSessionResult']) {
    assert.equal(reexported.includes(name), true, `types.ts must re-export ${name}`);
  }
});