<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>GameControl.Cli</RootNamespace>
    <AssemblyName>game-control</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\WindowsCapture.App\GameControlCli.cs" Link="GameControlCli.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WindowsCapture.Core\WindowsCapture.Core.csproj" />
  </ItemGroup>

</Project>
