"""Transport-independent Agent Runtime Service (S1 + S2 + S3 in-process slice).

Public DTOs, event cursors, filtering, pagination, size limits, and error codes
live in the submodules; ``LocalAgentRuntimeService`` implements the ports over
``RuntimeManager``-backed sessions.  The package must stay free of
UI/CLI/ACP/transport/framework imports.

Every public name is re-exported lazily (PEP 562) so that importing a pure
contract submodule (``commands`` / ``events`` / ``queries`` / ...) does not pull
in the implementation modules (``local`` / ``routing`` / ``history_store``) or
the session execution stack.  Accessing a name from this package still resolves
to the same object as importing it from its owning submodule.
"""

from __future__ import annotations

from importlib import import_module
from importlib.util import find_spec

__all__ = [
    "AgentRuntimeService",
    "ApprovalActionView",
    "ApprovalDecision",
    "AccessControlledAgentRuntimeService",
    "AccessRequest",
    "AclAuthorizer",
    "AclGrant",
    "DaemonAuthorizer",
    "ALL_RUNTIME_CAPABILITIES",
    "ARTIFACTS_LIST",
    "ARTIFACTS_READ",
    "ARTIFACTS_STAT",
    "ATTACHMENTS_READ",
    "ATTACHMENTS_WRITE",
    "AbortAttachmentCommand",
    "AbortAttachmentResult",
    "AppendAttachmentChunkCommand",
    "AppendAttachmentChunkResult",
    "AttachmentChunk",
    "AttachmentMetadata",
    "AttachmentRef",
    "BeginAttachmentCommand",
    "BeginAttachmentResult",
    "FinishAttachmentCommand",
    "FinishAttachmentResult",
    "HistoryAttachment",
    "ReadAttachmentQuery",
    "StatAttachmentQuery",
    "ArtifactChangedError",
    "ArtifactChunk",
    "ArtifactForbiddenError",
    "ArtifactMetadata",
    "ArtifactNotFoundError",
    "ArtifactOverflowError",
    "ArtifactPage",
    "ArtifactRef",
    "ArtifactUnavailableError",
    "CancelTurnCommand",
    "CancelTurnResult",
    "CatalogProjectProvider",
    "CatalogProjectListProvider",
    "ClearSessionGoalCommand",
    "ClosedError",
    "CloseSessionCommand",
    "CloseSessionResult",
    "CommandReceipt",
    "ConflictError",
    "ConfigOverflowError",
    "CreateSessionCommand",
    "CreateSessionResult",
    "DEFAULT_CHUNK_BYTES",
    "DEFAULT_MAX_EVENT_BYTES",
    "DEFAULT_SCAN_LIMIT",
    "DeleteSessionCommand",
    "DeleteSessionResult",
    "EditSessionGoalCommand",
    "EventCursor",
    "EventOverflowError",
    "EventTooLargeError",
    "EventFilter",
    "EventPage",
    "EventStream",
    "EventWatch",
    "EVENTS_READ",
    "EVENTS_WATCH",
    "HISTORY_LIMIT_DEFAULT",
    "HISTORY_LIMIT_MAX",
    "HISTORY_LIMIT_MIN",
    "HistoryEvent",
    "HistoryTooLargeError",
    "MAX_EVENT_BYTES",
    "MAX_RECONCILE_PROBE_TURNS",
    "MAX_RECONCILE_TURN_ID_BYTES",
    "MAX_RUNTIME_CONFIG_MCP_SERVERS",
    "MAX_RUNTIME_CONFIG_MODELS",
    "MAX_RUNTIME_CONFIG_TEXT_BYTES",
    "MAX_RUNTIME_CONFIG_THINKING_LEVELS",
    "MAX_SESSION_GOAL_OBJECTIVE_CHARS",
    "MAX_CURSOR_BYTES",
    "MAX_EXPECTED_REVISION_BYTES",
    "MAX_SCAN_LIMIT",
    "GetSessionQuery",
    "GetSessionGoalQuery",
    "GetRuntimeConfigQuery",
    "McpServerView",
    "PendingApprovalQuery",
    "PendingApprovalView",
    "PauseSessionGoalCommand",
    "ReconcileSessionQuery",
    "SessionRecoverabilityView",
    "TurnCoverageProbe",
    "InvalidArtifactCursorError",
    "InvalidArtifactPathError",
    "InvalidAccessContextError",
    "InvalidCursorError",
    "InvalidEventPayloadError",
    "InvalidRequestError",
    "InvalidSessionError",
    "LocalAgentRuntimeService",
    "LocalEventStream",
    "LocalEventWatch",
    "ListArtifactsQuery",
    "ListSessionsQuery",
    "McpServerStateView",
    "MIN_EVENT_BYTES",
    "MIN_SCAN_LIMIT",
    "NoActiveTurnError",
    "NotFoundError",
    "OpenSessionCommand",
    "OpenSessionResult",
    "RebindSessionCommand",
    "RebindSessionResult",
    "ReloadMcpCommand",
    "ReloadMcpResult",
    "ReadArtifactQuery",
    "ReadEventsQuery",
    "ReadSessionHistoryQuery",
    "ReplayGapError",
    "ResumeSessionGoalCommand",
    "RuntimeEvent",
    "RuntimeConfigView",
    "RuntimeServiceError",
    "RouterClosedError",
    "RuntimeManagerRouter",
    "RuntimeProject",
    "ManagerFactory",
    "ProjectProvider",
    "PermissionDeniedError",
    "Principal",
    "RenameSessionCommand",
    "RenameSessionResult",
    "SearchSessionsQuery",
    "SESSION_CREATE",
    "SESSION_DELETE",
    "SESSION_LIST",
    "SESSION_LIST_LIMIT_DEFAULT",
    "SESSION_LIST_LIMIT_MAX",
    "SESSION_LIST_LIMIT_MIN",
    "SESSION_LIST_OFFSET_MAX",
    "SESSION_RENAME",
    "SESSION_SEARCH",
    "SESSION_SEARCH_LIMIT_DEFAULT",
    "SESSION_SEARCH_LIMIT_MAX",
    "SESSION_SEARCH_LIMIT_MIN",
    "SESSION_SEARCH_OFFSET_MAX",
    "SESSION_SEARCH_TEXT_MAX",
    "SESSION_TITLE_MAX",
    "SESSION_CLOSE",
    "SESSION_GOAL",
    "SESSION_OPEN",
    "SESSION_READ",
    "SESSION_REBIND",
    "SESSION_THINKING",
    "PROJECT_THINKING",
    "PROJECT_LIST",
    "PROJECT_LIST_LIMIT_DEFAULT",
    "PROJECT_LIST_LIMIT_MAX",
    "PROJECT_LIST_LIMIT_MIN",
    "PROJECT_LIST_OFFSET_MAX",
    "PROJECT_LIST_VISIBILITY_MAX",
    "ProjectListItem",
    "ProjectListPage",
    "ProjectListProvider",
    "ProjectScopeAuthorizer",
    "ListProjectsQuery",
    "SESSION_MCP_RELOAD",
    "TURN_APPROVAL_READ",
    "TURN_APPROVAL_RESUME",
    "SessionView",
    "SessionGoalView",
    "SessionGoalResult",
    "SessionHistoryPage",
    "SessionListPage",
    "SessionMetadataItem",
    "SessionSearchPage",
    "SessionProjectContext",
    "SetThinkingLevelCommand",
    "SetThinkingLevelResult",
    "SetSessionGoalCommand",
    "SetProjectThinkingLevelCommand",
    "SetProjectThinkingLevelResult",
    "SteerTurnCommand",
    "SteerTurnResult",
    "StatArtifactQuery",
    "SteeringUnavailableError",
    "SubmitTurnCommand",
    "ResumeTurnCommand",
    "ResumeTurnResult",
    "TURN_CANCEL",
    "TURN_STEER",
    "TURN_SUBMIT",
    "TurnMismatchError",
    "UsageView",
    "bind_access",
]

#: Public name -> owning submodule (without the package prefix).
_LAZY_EXPORTS = {
    "ALL_RUNTIME_CAPABILITIES": "access",
    "ARTIFACTS_LIST": "access",
    "ARTIFACTS_READ": "access",
    "ARTIFACTS_STAT": "access",
    "ATTACHMENTS_READ": "access",
    "ATTACHMENTS_WRITE": "access",
    "AccessControlledAgentRuntimeService": "access",
    "AccessRequest": "access",
    "AclAuthorizer": "access",
    "AclGrant": "access",
    "DaemonAuthorizer": "access",
    "EVENTS_READ": "access",
    "EVENTS_WATCH": "access",
    "PROJECT_THINKING": "access",
    "PROJECT_LIST": "access",
    "ProjectScopeAuthorizer": "access",
    "Principal": "access",
    "SESSION_CLOSE": "access",
    "SESSION_CREATE": "access",
    "SESSION_DELETE": "access",
    "SESSION_GOAL": "access",
    "SESSION_LIST": "access",
    "SESSION_MCP_RELOAD": "access",
    "SESSION_OPEN": "access",
    "SESSION_READ": "access",
    "SESSION_REBIND": "access",
    "SESSION_RENAME": "access",
    "SESSION_SEARCH": "access",
    "SESSION_THINKING": "access",
    "TURN_APPROVAL_READ": "access",
    "TURN_APPROVAL_RESUME": "access",
    "TURN_CANCEL": "access",
    "TURN_STEER": "access",
    "TURN_SUBMIT": "access",
    "bind_access": "access",
    "ArtifactChunk": "artifacts",
    "ArtifactMetadata": "artifacts",
    "ArtifactPage": "artifacts",
    "ArtifactRef": "artifacts",
    "AbortAttachmentCommand": "attachments",
    "AbortAttachmentResult": "attachments",
    "AppendAttachmentChunkCommand": "attachments",
    "AppendAttachmentChunkResult": "attachments",
    "AttachmentChunk": "attachments",
    "AttachmentMetadata": "attachments",
    "AttachmentRef": "attachments",
    "BeginAttachmentCommand": "attachments",
    "BeginAttachmentResult": "attachments",
    "FinishAttachmentCommand": "attachments",
    "FinishAttachmentResult": "attachments",
    "ReadAttachmentQuery": "attachments",
    "StatAttachmentQuery": "attachments",
    "DEFAULT_CHUNK_BYTES": "artifacts",
    "ListArtifactsQuery": "artifacts",
    "MAX_CURSOR_BYTES": "artifacts",
    "MAX_EXPECTED_REVISION_BYTES": "artifacts",
    "ReadArtifactQuery": "artifacts",
    "StatArtifactQuery": "artifacts",
    "ApprovalDecision": "commands",
    "CancelTurnCommand": "commands",
    "CancelTurnResult": "commands",
    "CloseSessionCommand": "commands",
    "CloseSessionResult": "commands",
    "CommandReceipt": "commands",
    "McpServerStateView": "commands",
    "OpenSessionCommand": "commands",
    "OpenSessionResult": "commands",
    "RebindSessionCommand": "commands",
    "RebindSessionResult": "commands",
    "ReloadMcpCommand": "commands",
    "ReloadMcpResult": "commands",
    "ResumeTurnCommand": "commands",
    "ResumeTurnResult": "commands",
    "SetProjectThinkingLevelCommand": "commands",
    "SetProjectThinkingLevelResult": "commands",
    "SetThinkingLevelCommand": "commands",
    "SetThinkingLevelResult": "commands",
    "SteerTurnCommand": "commands",
    "SteerTurnResult": "commands",
    "SubmitTurnCommand": "commands",
    "ArtifactChangedError": "errors",
    "ArtifactForbiddenError": "errors",
    "ArtifactNotFoundError": "errors",
    "ArtifactOverflowError": "errors",
    "ArtifactUnavailableError": "errors",
    "ClosedError": "errors",
    "ConfigOverflowError": "errors",
    "ConflictError": "errors",
    "EventOverflowError": "errors",
    "EventTooLargeError": "errors",
    "HistoryTooLargeError": "errors",
    "InvalidAccessContextError": "errors",
    "InvalidArtifactCursorError": "errors",
    "InvalidArtifactPathError": "errors",
    "InvalidCursorError": "errors",
    "InvalidEventPayloadError": "errors",
    "InvalidRequestError": "errors",
    "InvalidSessionError": "errors",
    "NoActiveTurnError": "errors",
    "NotFoundError": "errors",
    "PermissionDeniedError": "errors",
    "ReplayGapError": "errors",
    "RuntimeServiceError": "errors",
    "SteeringUnavailableError": "errors",
    "TurnMismatchError": "errors",
    "DEFAULT_MAX_EVENT_BYTES": "events",
    "DEFAULT_SCAN_LIMIT": "events",
    "EventCursor": "events",
    "EventFilter": "events",
    "EventPage": "events",
    "MAX_EVENT_BYTES": "events",
    "MAX_SCAN_LIMIT": "events",
    "MIN_EVENT_BYTES": "events",
    "MIN_SCAN_LIMIT": "events",
    "ReadEventsQuery": "events",
    "RuntimeEvent": "events",
    "ClearSessionGoalCommand": "goal_management",
    "EditSessionGoalCommand": "goal_management",
    "MAX_SESSION_GOAL_OBJECTIVE_CHARS": "goal_management",
    "PauseSessionGoalCommand": "goal_management",
    "ResumeSessionGoalCommand": "goal_management",
    "SessionGoalResult": "goal_management",
    "SetSessionGoalCommand": "goal_management",
    "HISTORY_LIMIT_DEFAULT": "history",
    "HISTORY_LIMIT_MAX": "history",
    "HISTORY_LIMIT_MIN": "history",
    "HistoryAttachment": "history",
    "HistoryEvent": "history",
    "ListSessionsQuery": "history",
    "ListProjectsQuery": "project_list",
    "PROJECT_LIST_LIMIT_DEFAULT": "project_list",
    "PROJECT_LIST_LIMIT_MAX": "project_list",
    "PROJECT_LIST_LIMIT_MIN": "project_list",
    "PROJECT_LIST_OFFSET_MAX": "project_list",
    "PROJECT_LIST_VISIBILITY_MAX": "project_list",
    "ProjectListItem": "project_list",
    "ProjectListPage": "project_list",
    "ProjectListProvider": "project_list",
    "ReadSessionHistoryQuery": "history",
    "SESSION_LIST_LIMIT_DEFAULT": "history",
    "SESSION_LIST_LIMIT_MAX": "history",
    "SESSION_LIST_LIMIT_MIN": "history",
    "SESSION_LIST_OFFSET_MAX": "history",
    "SessionHistoryPage": "history",
    "SessionListPage": "history",
    "SessionMetadataItem": "history",
    "CreateSessionCommand": "session_management",
    "CreateSessionResult": "session_management",
    "DeleteSessionCommand": "session_management",
    "DeleteSessionResult": "session_management",
    "RenameSessionCommand": "session_management",
    "RenameSessionResult": "session_management",
    "SESSION_TITLE_MAX": "session_management",
    "SESSION_SEARCH_LIMIT_DEFAULT": "session_management",
    "SESSION_SEARCH_LIMIT_MAX": "session_management",
    "SESSION_SEARCH_LIMIT_MIN": "session_management",
    "SESSION_SEARCH_OFFSET_MAX": "session_management",
    "SESSION_SEARCH_TEXT_MAX": "session_management",
    "SearchSessionsQuery": "session_management",
    "SessionProjectContext": "session_management",
    "SessionSearchPage": "session_management",
    "LocalAgentRuntimeService": "local",
    "LocalEventStream": "local",
    "LocalEventWatch": "local",
    "AgentRuntimeService": "ports",
    "EventStream": "ports",
    "EventWatch": "ports",
    "ApprovalActionView": "queries",
    "GetSessionGoalQuery": "queries",
    "GetSessionQuery": "queries",
    "PendingApprovalQuery": "queries",
    "PendingApprovalView": "queries",
    "SessionGoalView": "queries",
    "SessionView": "queries",
    "UsageView": "queries",
    "MAX_RECONCILE_PROBE_TURNS": "recovery",
    "MAX_RECONCILE_TURN_ID_BYTES": "recovery",
    "ReconcileSessionQuery": "recovery",
    "SessionRecoverabilityView": "recovery",
    "TurnCoverageProbe": "recovery",
    "CatalogProjectProvider": "routing",
    "CatalogProjectListProvider": "routing",
    "ManagerFactory": "routing",
    "ProjectProvider": "routing",
    "RouterClosedError": "routing",
    "RuntimeManagerRouter": "routing",
    "RuntimeProject": "routing",
    "GetRuntimeConfigQuery": "runtime_config",
    "MAX_RUNTIME_CONFIG_MCP_SERVERS": "runtime_config",
    "MAX_RUNTIME_CONFIG_MODELS": "runtime_config",
    "MAX_RUNTIME_CONFIG_TEXT_BYTES": "runtime_config",
    "MAX_RUNTIME_CONFIG_THINKING_LEVELS": "runtime_config",
    "McpServerView": "runtime_config",
    "RuntimeConfigView": "runtime_config",
}


def __getattr__(name: str) -> object:
    """Resolve one public re-export on first access (PEP 562)."""
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is not None:
        value = getattr(import_module(f"{__name__}.{module_name}"), name)
        globals()[name] = value
        return value
    # Preserve pre-lazy behavior for ``package.submodule`` attribute access:
    # a real submodule resolves on demand, anything else is an AttributeError.
    if name.isidentifier() and not name.startswith("_") and find_spec(f"{__name__}.{name}"):
        return import_module(f"{__name__}.{name}")
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(__all__)
