/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#ecf0ff",
        "surface-container": "#ffffff",
        "error-container": "#ffdad6",
        "primary": "#004ac6",
        "on-secondary-container": "#596372",
        "on-background": "#191c1d",
        "surface-container-low": "#f3f4f5",
        "inverse-surface": "#2e3132",
        "on-tertiary-fixed-variant": "#404758",
        "secondary-fixed-dim": "#bdc7d8",
        "tertiary": "#4e5566",
        "on-error": "#ffffff",
        "background": "#f8f9fa",
        "on-primary": "#ffffff",
        "outline-variant": "#c3c6d7",
        "surface-dim": "#d9dadb",
        "primary-fixed": "#dbe1ff",
        "tertiary-container": "#666d7f",
        "surface-variant": "#e1e3e4",
        "divider": "#e5e7eb",
        "secondary-fixed": "#d9e3f4",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e1e3e4",
        "outline": "#737686",
        "surface-bright": "#f8f9fa",
        "on-secondary": "#ffffff",
        "surface-tint": "#0053db",
        "error": "#ba1a1a",
        "secondary-container": "#d6e0f1",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1d",
        "on-secondary-fixed-variant": "#3e4755",
        "on-tertiary-fixed": "#141b2b",
        "on-primary-fixed-variant": "#003ea8",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#00174b",
        "text-muted": "#6b7280",
        "editor-selection": "#dbeafe",
        "inverse-primary": "#b4c5ff",
        "on-surface-variant": "#434655",
        "tertiary-fixed-dim": "#c0c6db",
        "on-secondary-fixed": "#121c28",
        "on-primary-container": "#eeefff",
        "secondary": "#555f6d",
        "tertiary-fixed": "#dce2f7",
        "surface-container-high": "#e7e8e9",
        "primary-fixed-dim": "#b4c5ff",
        "surface": "#f8f9fa",
        "text-high-contrast": "#111827",
        "primary-container": "#2563eb"
      },
      spacing: {
        "sidebar-width": "240px",
        "panel-padding": "12px",
        "gutter": "16px",
        "unit": "4px",
        "margin": "24px"
      },
      fontFamily: {
        kbd: ["JetBrains Mono", "monospace"],
        "code-md": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
